apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z flask-api-db 5432; do echo waiting for db; sleep 2; done;",
            ]
      containers:
        - name: flask-api
          image: mouhagueye01/flask-app:2.0.0
          ports:
            - containerPort: 5000
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: flask-api-config
                  key: DB_URL
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /users/health/ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /users/health/live
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
